INCLUDE: ["config_share.yaml"] # 可以包含多个其他 *.yaml 文件

SERVER_TYPE: 11     #服务器类型
SERVER_ID: 11001     #服务器编号:11001
SERVER_NAME: "CSGO开奖服务器"  #服务器名称
SERVER_ADDR: "127.0.0.1"  #服务器外部地址
SERVER_ADDR_INTERNAL: "127.0.0.1"  #服务器内部地址
LISTEN_PORT_FOR_WEB_API_CLIENT: 11511  #监听 http对外客户端请求
LISTEN_PORT_FOR_WEB_API_SERVER: 11611  #监听 http对内服务器间请求

DELAY_LOTTERY_TIME: 10800  #比赛结束延时开奖的时间(3*60*60秒=3小时)
BLOCKED_BEFORE_TIME: 300   #比赛滚盘投注项封禁前无效时间(5*60秒=5分钟)