INCLUDE: ["config_share.yaml","config_hall_secret.yaml"] # 可以包含多个其他 *.yaml 文件

SERVER_TYPE: 6     #服务器类型
SERVER_ID: 7001     #服务器编号:5000开头

REDIS_SERVER_DATABASE: 0             #redis数据库序号

SERVER_NAME: "社交广场1"  #服务器名称
SERVER_ADDR: "127.0.0.1"  #服务器外部地址
SERVER_ADDR_INTERNAL: "127.0.0.1"  #服务器内部地址
LISTEN_PORT_FOR_CLIENT: 7111  #监听Websocket客户端连接端口
LISTEN_PORT_FOR_CLIENT_TCP: 7311  #监听 TCP 客户端的链接
LISTEN_PORT_FOR_WEB_API_CLIENT: 7511  #监听 http对外客户端请求
LISTEN_PORT_FOR_WEB_API_SERVER: 7611  #监听 http对内服务器间请求