# 若要加配置、改配置名,请一定在打包脚本 build_linux_yaml_template.py 的模板上也同时加上

INCLUDE: [] # 可以包含多个其他 *.yaml 文件

##国内版短信模板
ALIYU_ACCESSKEYID: "LTAI4FdUu8fXogvv9penpDCK"                           #阿里云短信accesskeyId
ALIYU_ACCESSKEYSECRET: "mUe3dSYqxCAo3X5HvSdiInQt7690aG"         #阿里云短信accesskeySecret
ALIYU_AREA: "cn-hangzhou"                                       #阿里云地区
ALIYU_SIGNNAME: "柠檬畅聊"                                        #阿里云短信模板名字
ALIYU_TEMPLEATECODE: "SMS_180350717"                            #阿里云短信模板代号

##国际版短信模板
ALIYU_SIGNNAME_INTERNATIONAL: "柠檬畅聊国际"                                        #阿里云短信模板名字
ALIYU_TEMPLEATECODE_INTERNATIONAL: "SMS_197896950"                            #阿里云短信模板代号

##腾讯云短信模板
TC_TEMPLATE_ID_CODE: "柠檬畅聊国际"                                        #阿里云短信模板名字
TC_SMS_SDK_APPID_CODE: "SMS_197896950"                            #阿里云短信模板代号

TC_SMS_LOGOUT_FAILED_TEMPLATE_ID: "705285"                                        #腾讯云用户注销失败短信模板名字
TC_SMS_LOGOUT_SUCCESS_TEMPLATE_ID: "705282"                                       #腾讯云用户注销成功短信模板名字
TC_SMS_WARNING_TEMPLATE_ID: "766692"                                              #腾讯云预警功能短信模板名字
TC_SMS_SDK_APPID: "1400111500"                                                    #腾讯云SDKAppId
TC_SMS_SIGN: "柠檬畅聊"  #腾讯云签名
TC_SMS_SECRETID: "AKIDLRs45skfuLZZ7O87etzoOk6KHyPp7E1Z"
TC_SMS_SECRETKEY: "a3F9rXM44rYWENBy94JI3Wryn5SZPffS"

##应用微信appid
# appcode=100 使用
WEIXIN_APPID_100: "wx27682f51b810f0c2"                              #微信appid
WEIXIN_APPSECRET_100: "28c78426a9e5ac167c56554259430efb"            #微信appsecret

#apkcode=101 使用
WEIXIN_APPID_101: "wxce0ea7527a63f28d"                              #微信appid
WEIXIN_APPSECRET_101: "9df014d7ed57b41c0c1f3cc6b4f85137"            #微信appsecret
WEIXIN_URL: "https://api.weixin.qq.com/sns/oauth2/access_token?appid=%s&secret=%s&code=%s&grant_type=authorization_code"#微信验证url
WEIXIN_USERURL: "https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s"
##小程序微信appid
# appcode=100 使用
WEIXIN_SGAME_APPID_100: "wx414f06b4024739c8"
WEIXIN_SGAME_SECRET_100: "645661043e2b05624c3e1bb9bec71c3b"
# appcode=101 使用
WEIXIN_SGAME_APPID_101: "wx905904883fc074d3"
WEIXIN_SGAME_SECRET_101: "98844f416ebfdbd23a7238c592e08a30"


##极光快速登录appid
# appcode=100 使用
JG_APPKEY_100: "36d53261f51f9fffe4980a77"
JG_SECRET_100: "8e6854a3c07bba4e0363fc37"
#apkcode=101 使用
JG_APPKEY_101: "95279e7cbe6af3de678647ee"
JG_SECRET_101: "4c87a3377d9594b297be41c9"


JH_AUTHPEOPLEIDKEY: "fd28afdb60abcb05f3b221f55a5f1c18"
JH_AUTHBANKIDKEY: "3f15b88acd0a636682f8648c118238ef"

MOB_APPKEY: "2f34428f2351b"
MOB_SECRET: "bd15bf06f8dcba4aa18a14d8b088b9e6"
MOB_URL: "http://api.push.mob.com/v3/push/createPush"
MOB_URL_V2: "http://api.push.mob.com/v2/push"


#秒到支付配置信息
MD_PAY_APPID: "wx414f06b4024739c8"
MD_PAY_KEY: "aa403187f550527bf7cda6affb0660ab"
MD_PAY_MERCHANTNO: "15099973008"
MD_PAY_AGENCYCODE: "86038810"
MD_PAY_NOTIFY_URL: "http://tf1.lemonchat.cn:2601/miaodao"

#通联支付配置信息
TL_PAY_APPID: "wx414f06b4024739c8"
TL_PAY_KEY: "64336113WEIwei"
TL_PAY_MERCHANTNO: "56058104816WR4N"
TL_PAY_MERCHANTAPPID: "00184603"
TL_PAY_NOTIFY_URL: "http://tf1.lemonchat.cn:2601/tonglian"


# 汇潮配置信息
HUICHAO_URL: "https://gwapi.yemadai.com/" # url
HUICHAO_MERCHANTNO: "50592" # 商户号
HUICHAO_PAY_CALLBACK_URL: "http://47.112.142.227:2601/huichaopay" # 汇潮支付回调地址
HUICHAO_PAY_DF_CALLBACK_URL: "http://47.112.142.227:2601/huichaoDF" # 汇潮支付 代付回调地址
HUICHAO_WXCOMPANYNO: "sweep-b90d814d534a4b219ab1fe0983f248e9"
HUICHAO_ZFBCOMPANYNO: "sweep-d3a493fa16d5475f9c655eda30c385a7"
HUICHAO_WXAPPID: "wx905904883fc074d3"

#统统付支付配置
TTP_URL: "http://117.48.192.183/cgi-bin/" # url
TTP_PAY_CALLBACK_URL: "http://47.112.142.227:2601/tongtongpay" # 统统付支付回调地址
TTP_SYSCODE: "20000115" #系统号
TTP_MERCHANTNO: "9062000058" # 商户号
TTP_MD5_KEY: "b11519815gzgas115fip6gzpu2k13"

TTP_WXAPPID: "wx905904883fc074d3"

#云通商支付配置
YTS_WXAPPID: "app_839876f98fb44819b7"
YTS_URL: "http://api.foceplay.com/v2/"
YTS_PAY_CALLBACK_URL: "http://47.112.142.227:2601/ytspay"
YTS_MD5_KEY: "sk_live_d2068cb4b1554719818f"

###音频合成服务器地址
VOICE_VEDIO_MIX_URL: "http://192.168.100.99:5000/overdub"