# 若要加配置、改配置名,请一定在打包脚本 build_linux_yaml_template.py 的模板上也同时加上

INCLUDE: ["config_share.yaml","config_hall_secret.yaml"] # 可以包含多个其他 *.yaml 文件
SERVER_TYPE: 1     #服务器类型
SERVER_ID: 1001     #服务器编号 新增服id递增取值区间(1001-1999)
SERVER_NAME: "登录服1"  #服务器名称
SERVER_ADDR: "127.0.0.1"  #服务器外部地址
SERVER_ADDR_INTERNAL: "127.0.0.1"  #服务器内部地址
LISTEN_PORT_FOR_CLIENT: 1111  #监听Websocket客户端连接端口
LISTEN_PORT_FOR_CLIENT_TCP: 1311  #监听 TCP 客户端的链接
LISTEN_PORT_FOR_WEB_API_CLIENT: 1511  #监听 http对外客户端请求
LISTEN_PORT_FOR_WEB_API_SERVER: 1611  #监听 http对内服务器间请求
TLS_CRT_FILE_PATH: "" # crt 文件路径. 比如 www.test.com.crt 或 ./test/www.test.com.crt, 值为空串时变成走 ws 协议
TLS_KEY_FILE_PATH: "" # key 文件路径. 比如 www.test.com.key 或 ./test/www.test.com.key, 值为空串时变成走 ws 协议
VERSION_NUMBER: "1.0.0" # 版本号.升级了版本号记得到 build_linux_yaml_template.py 打包模板修改一下