package h5_wish

import (
	"game_server/easygo"
)

var UpRpc = map[string]easygo.Pair{
	"RpcLogin":                easygo.Pair{"h5_wish.LoginReq", "h5_wish.LoginResp"},
	"RpcQueryBox":             easygo.Pair{"h5_wish.QueryBoxReq", "h5_wish.QueryBoxResp"},
	"RpcQueryBoxProductName":  easygo.Pair{"base.Empty", "h5_wish.BoxProductNameResp"},
	"RpcSearchFound":          easygo.Pair{"base.Empty", "h5_wish.BoxProductNameResp"},
	"RpcProductShow":          easygo.Pair{"base.Empty", "h5_wish.ProductShowResp"},
	"RpcGetCoin":              easygo.Pair{"base.Empty", "h5_wish.GetCoinResp"},
	"RpcGetUseInfo":           easygo.Pair{"h5_wish.UserInfoReq", "h5_wish.UserInfoResp"},
	"RpcAddCoin":              easygo.Pair{"h5_wish.AddCoinReq", "h5_wish.AddCoinResp"},
	"RpcAddGold":              easygo.Pair{"h5_wish.AddGoldReq", "h5_wish.AddGoldResp"},
	"RpcHomeMessage":          easygo.Pair{"base.Empty", "h5_wish.HomeMessageResp"},
	"RpcProtector":            easygo.Pair{"base.Empty", "h5_wish.ProtectorDataResp"},
	"RpcMenu":                 easygo.Pair{"base.Empty", "h5_wish.MenuResp"},
	"RpcProductBrand":         easygo.Pair{"base.Empty", "h5_wish.ProductBrandListResp"},
	"RpcSearchBox":            easygo.Pair{"h5_wish.SearchBoxReq", "h5_wish.SearchBoxResp"},
	"RpcBrandList":            easygo.Pair{"base.Empty", "h5_wish.BrandListResp"},
	"RpcProductTypeList":      easygo.Pair{"base.Empty", "h5_wish.TypeListResp"},
	"RpcGetRandProduct":       easygo.Pair{"h5_wish.DareReq", "h5_wish.RandProductResp"},
	"RpcGetDareMessage":       easygo.Pair{"base.Empty", "h5_wish.DareMessageResp"},
	"RpcDefenderCarousel":     easygo.Pair{"base.Empty", "h5_wish.DefenderMsgResp"},
	"RpcGotWishCarousel":      easygo.Pair{"base.Empty", "h5_wish.GotWishPlayerResp"},
	"RpcDareRecommend":        easygo.Pair{"base.Empty", "h5_wish.DareRecommendResp"},
	"RpcRankings":             easygo.Pair{"base.Empty", "h5_wish.RankingResp"},
	"RpcMyRecord":             easygo.Pair{"base.Empty", "h5_wish.MyRecordResp"},
	"RpcMyDare":               easygo.Pair{"h5_wish.MyDareReq", "h5_wish.MyDareResp"},
	"RpcBoxInfo":              easygo.Pair{"h5_wish.BoxReq", "h5_wish.BoxResp"},
	"RpcDareList":             easygo.Pair{"h5_wish.DareReq", "h5_wish.DareResp"},
	"RpcProductDetail":        easygo.Pair{"h5_wish.ProductDetailReq", "h5_wish.ProductDetail"},
	"RpcDareRecord":           easygo.Pair{"h5_wish.DareRecordReq", "h5_wish.DareRecordResp"},
	"RpcWish":                 easygo.Pair{"h5_wish.WishReq", "h5_wish.WishResp"},
	"RpcDoDare":               easygo.Pair{"h5_wish.DoDareReq", "h5_wish.DoDareResp"},
	"RpcBoxList":              easygo.Pair{"base.Empty", "h5_wish.BoxListResp"},
	"RpcBoxProduct":           easygo.Pair{"h5_wish.DareReq", "h5_wish.BoxProductResp"},
	"RpcTryOnce":              easygo.Pair{"base.Empty", "base.Empty"},
	"RpcMyWish":               easygo.Pair{"h5_wish.MyWishReq", "h5_wish.ProductResp"},
	"RpcMyAllWish":            easygo.Pair{"h5_wish.MyWishReq", "h5_wish.ProductResp"},
	"RpcGetCollectionBox":     easygo.Pair{"h5_wish.DataPageReq", "h5_wish.MyCollectedBoxResp"},
	"RpcGetAllCollectionBox":  easygo.Pair{"base.Empty", "h5_wish.MyCollectedBoxResp"},
	"RpcCollectionBox":        easygo.Pair{"h5_wish.CollectionBoxReq", "h5_wish.DefaultResp"},
	"RpcGetWishBoxList":       easygo.Pair{"h5_wish.DataPageReq", "h5_wish.MyCollectedBoxResp"},
	"RpcGetAllWishBoxList":    easygo.Pair{"base.Empty", "h5_wish.MyCollectedBoxResp"},
	"RpcDelWishBox":           easygo.Pair{"h5_wish.WishBoxReq", "h5_wish.DefaultResp"},
	"RpcExchangeBox":          easygo.Pair{"h5_wish.WishBoxReq", "h5_wish.DefaultResp"},
	"RpcRecycleGoods":         easygo.Pair{"h5_wish.WishBoxReq", "h5_wish.DefaultResp"},
	"RpcGetAddressList":       easygo.Pair{"h5_wish.DataPageReq", "h5_wish.AddressListResp"},
	"RpcAddAddress":           easygo.Pair{"h5_wish.WishAddress", "h5_wish.DefaultResp"},
	"RpcEditAddress":          easygo.Pair{"h5_wish.WishAddress", "h5_wish.DefaultResp"},
	"RpcRemoveAddress":        easygo.Pair{"h5_wish.RemoveAddressReq", "h5_wish.DefaultResp"},
	"RpcGetUnReadWishNum":     easygo.Pair{"base.Empty", "h5_wish.JustNumberResp"},
	"RpcToExchangeWishNum":    easygo.Pair{"base.Empty", "h5_wish.JustNumberResp"},
	"RpcAreaPostage":          easygo.Pair{"base.Empty", "h5_wish.PostageResp"},
	"RpcRecycleRatio":         easygo.Pair{"base.Empty", "h5_wish.JustNumberResp"},
	"RpcGetConfig":            easygo.Pair{"base.Empty", "h5_wish.ConfigResp"},
	"RpcGetUserIdBankCards":   easygo.Pair{"base.Empty", "h5_wish.BankCardResp"},
	"RpcRecycleDesc":          easygo.Pair{"base.Empty", "h5_wish.DefaultResp"},
	"RpcSetBoxPreSale":        easygo.Pair{"h5_wish.PresaleReq", "base.Empty"},
	"RpcSoldOutBox":           easygo.Pair{"h5_wish.DealBoxReq", "base.Empty"},
	"RpcReplenishBox":         easygo.Pair{"h5_wish.DealBoxReq", "base.Empty"},
	"RpcSetBoxExpress":        easygo.Pair{"h5_wish.SetExpressInfoReq", "base.Empty"},
	"RpcGetBoxExpress":        easygo.Pair{"h5_wish.GetExpressInfoReq", "h5_wish.GetExpressInfoResp"},
	"RpcCoinToDiamond":        easygo.Pair{"h5_wish.CoinToDiamondReq", "h5_wish.CoinToDiamondResq"},
	"RpcDiamondRechargeList":  easygo.Pair{"base.Empty", "h5_wish.DiamondRechargeResp"},
	"RpcDiamondChangeLogList": easygo.Pair{"h5_wish.DiamondChangeLogReq", "h5_wish.DiamondChangeLogResp"},
	"RpcGetPriceSection":      easygo.Pair{"base.Empty", "h5_wish.PriceSectionResp"},
	"RpcBatchDare":            easygo.Pair{"h5_wish.BatchDareReq", "h5_wish.BatchDareResp"},
	"RpcPlayCfg":              easygo.Pair{"base.Empty", "h5_wish.PlayCfgResp"},
	"RpcSumNum":               easygo.Pair{"h5_wish.SumReq", "h5_wish.SumNumResp"},
	"RpcSumMoney":             easygo.Pair{"h5_wish.SumMoneyReq", "h5_wish.SumMoneyResp"},
	"RpcGive":                 easygo.Pair{"h5_wish.GiveReq", "h5_wish.GiveResp"},
	"RpcActPoolList":          easygo.Pair{"base.Empty", "h5_wish.ActPoolResp"},
	"RpcActPoolRule":          easygo.Pair{"h5_wish.ActPoolRuleReq", "h5_wish.ActPoolRuleResp"},
	"RpcActName":              easygo.Pair{"h5_wish.ActNameReq", "h5_wish.ActNameResp"},
	"RpcActOpenStatus":        easygo.Pair{"base.Empty", "h5_wish.ActOpenStatusResp"},
	"RpcRechargeActStatus":    easygo.Pair{"base.Empty", "h5_wish.ActOpenStatusResp"},
	"RpcReportWishLog":        easygo.Pair{"h5_wish.TypeReq", "base.Empty"},
	"RpcGetRechargeAct":       easygo.Pair{"base.Empty", "h5_wish.RechargeActResp"},
	"RpcGetRechargeLogs":      easygo.Pair{"h5_wish.DataPageReq", "h5_wish.RechargeLogsResp"},
}

var DownRpc = map[string]easygo.Pair{}
